const copy = {
    title0: "Arch Lunar",
    title1: "Art Archive",
    description: "An extension of Arch Mission’s commitment to preserve human culture in outer space, this archive represents a snapshot of contemporary art in the year 2022, a time capsule containing responses to the moment by a diverse yet interconnected group of artists.",
    footer: "The first ever global contemporary art archive on the moon.",
    heroImg: "",
    links: [
        { href: "https://www.archmission.org/", content: "arch mission" },
        { href: "https://x.com/arch_lunar", content: "x" },
        { href: "https://instagram/arch_lunar_art_archive", content: "instagram" },
        { href: "https://warpcast.com/art-archive", content: "farcaster" },
        { href: "https://discord.gg/uvFsFtqgBG", content: "discord" },
    ],
    artists: [
        "Aaron Naves ",
        "Adrian Pijoan",
        "Alex Anderson ",
        "Alex Mackin Dolan ",
        "Alex Seton",
        "Alice Wang",
        "Allen Hung-Lun Chen",
        "Allie Zhang",
        "Amalia Ulman",
        "Anarchy Dance Theatre",
        "Andreas Rønholt Schmidt",
        "Andrew Hahn",
        "Andrew Norman Wilson",
        "AP Nguyen",
        "Asha Schecter",
        "Asya Nur",
        "Aura Rosenberg",
        "Aushin Chang",
        "Barak Zemer",
        "Bart Seng",
        "Bjarne Bare",
        "Brigid Mason",
        "Candice Jee in cooperation with Yaya Huwat",
        "Carol Strober",
        "Casey Kauffmann",
        "Chen Chien Jung",
        "Chen Zi Yin",
        "Chia Lee",
        "Chris Hanke",
        "Cindy Conrad",
        "Dakota Blue",
        "Danielle Dean",
        "Donel Williams",
        "Edgar Fabián Frías",
        "Elliot Kaufman",
        "Emily Yang 艾蜜莉",
        "Emma Hazen",
        "Erik Frydenborg",
        "Erin Calla Watson",
        "Ewa Wojciak",
        "Filip Gilissen",
        "Fiona Connor",
        "Fung Yee Lick",
        "Gabby Davis",
        "Gauntlett Cheng",
        "Giacomo Giannantonio",
        "Gianna Surangkanjanajai",
        "Gina Mei",
        "Graham Epstein",
        "Hanna Rose Stewart",
        "Henri McMaster",
        "hooz",
        "Horacio Alcolea Crespo",
        "Ian Stanton",
        "Idolate",
        "Ilja Karilampi",
        "Jacob Cruzen",
        "Jared Madere",
        "Jared Richardson (JVY)",
        "Jasia Rabiej",
        "jason meadows",
        "Jasper Spicero",
        "Jaybe Lee",
        "Jeff Beal",
        "Jeffrey Scudder",
        "Jennifer Zhang",
        "Jessica Hang",
        "Johnny Forever Nawracaj (sound by Gambletron) ",
        "Jon Pylypchuk",
        "Jonathan Moore",
        "JPW3",
        "julia yerger",
        "Juliana Halpert",
        "Julie (peter. s)",
        "Kaiyen Tu",
        "Kate Sansom",
        "Kathy Haddad",
        "Ken Twitchell",
        "Lane Stewart",
        "Lin Pei-Yao",
        "Lindsay Lawson",
        "Liya Yu",
        "Liz Magic Lazer",
        "Louie Shirase",
        "Luis Serrano",
        "Maria Petschnig",
        "Martin Lammert",
        "Mathias Toubro",
        "Matt Siegle (candy machine)",
        "Matthew Cherrie",
        "Michael Pollard",
        "Ming Yao CHANG",
        "Mitchell Syrop",
        "MM33",
        "Mooncat",
        "Nao Bustamante",
        "natalie astraea",
        "Negashi Armada + Mickey Goodman",
        "Ni Hao",
        "Nick (peter s.)",
        "OUCHHH",
        "Olammy",
        "Paige K.B.",
        "Paulson Lee",
        "Peggy Peiting Huang",
        "Peter Schulman",
        "Rachel Zaretsky Radimir Koch",
        "Ralph Kuo Chiang Wu ",
        "Rasmus Røhling ",
        "Remilia Corp ",
        "RESEARCH Publications ",
        "Retro1999",
        "Robin Sparkes",
        "Sam Anderson",
        "Sam Mason",
        "Sarah Rara",
        "Scott Benzel",
        "Scroll",
        "Seyoung Yoon",
        "Shana Moulton ",
        "Shang-Ru Lin ",
        "Shang-Yang Wu",
        "So Youn Lee",
        "Sylvia Hardy",
        "The Conversationalist ",
        "Tobias Sprictig",
        "Tore Wallert",
        "Travis Diehl",
        "Viola Morini ",
        "Wednesday Kim ",
        "Will Wharton",
        "Wyatt Naoki Conlon ",
        "Xtra",
        "Zhuxue Deren ",
        "Zuzanna Bartoszek",
    ]
}
export default copy;